name: renasyaa_fb
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  icon_decoration: ^2.0.2
  font_awesome_flutter: ^10.7.0
  simple_icons: ^10.1.3
  universal_html: ^2.2.4
  english_words: ^4.0.0
  url_launcher: ^6.2.5
  firebase_storage: ^11.6.7
  image_picker: ^1.0.7
  firebase_auth: ^4.17.6
  google_sign_in: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
